extends SceneTree


func _init() -> void:
	call_deferred("_run")


func _run() -> void:
	var manager := AchievementManager.new()
	root.add_child(manager)
	manager.pile_round_started.emit(3, true)
	manager.pile_placement_resolved.emit(0, [1, 1, 1] as Array[int], false)
	assert(not manager.unlocked.has(&"family_photo"))
	manager.pile_placement_resolved.emit(0, [0, 2, 2] as Array[int], true)
	assert(not manager.unlocked.has(&"one_at_a_time"))
	manager.pile_round_started.emit(4, true)
	manager.life_lost.emit()
	manager.pile_placement_resolved.emit(0, [1, 1, 1, 1] as Array[int], false)
	assert(manager.unlocked.has(&"family_photo"))
	manager.unlocked.clear()
	manager.pile_round_started.emit(4, true)
	manager.pile_placement_resolved.emit(0, [0, 2, 2, 2] as Array[int], true)
	assert(manager.unlocked.has(&"one_at_a_time"))
	manager.pile_placement_resolved.emit(1, [1, 1, 1, 1] as Array[int], false)
	assert(not manager.unlocked.has(&"family_photo"))
	manager.unlocked.clear()
	manager.pile_round_started.emit(5, true)
	manager.pile_placement_resolved.emit(0, [1, 2, 2, 2, 2] as Array[int], false)
	manager.pile_placement_resolved.emit(1, [1, 1, 2, 2, 2] as Array[int], false)
	manager.pile_placement_resolved.emit(0, [0, 1, 2, 2, 2] as Array[int], true)
	assert(not manager.unlocked.has(&"one_at_a_time"))
	manager.pile_round_started.emit(5, true)
	manager.pile_placement_resolved.emit(0, [1, 1, 1, 1, 1] as Array[int], false)
	assert(manager.unlocked.has(&"family_photo"))
	manager.unlocked.clear()
	manager.pile_round_started.emit(4, false)
	manager.pile_placement_resolved.emit(0, [1, 1, 1, 1] as Array[int], false)
	assert(not manager.unlocked.has(&"family_photo"))
	var palette_manager := ColorPaletteManager.new()
	root.add_child(palette_manager)
	palette_manager.load_progress()
	assert(not palette_manager.select(&"solid_gold"))
	manager.achievement_unlocked.connect(func(data: AchievementData) -> void:
		palette_manager.unlock_for_achievement(data.id)
	)
	for data in manager.definitions:
		if data.id not in [&"all_achievements", &"family_photo"]:
			manager.unlock(data.id, false)
	assert(not manager.unlocked.has(&"all_achievements"))
	manager.unlock(&"family_photo")
	assert(manager.unlocked.has(&"all_achievements"))
	assert(palette_manager.select(&"solid_gold"))
	assert(palette_manager.find(&"solid_gold").colors.size() == 10)
	assert(not manager.unlock(&"all_achievements"))
	# A save made before the meta achievement existed must also qualify.
	var config := ConfigFile.new()
	assert(config.load(AchievementManager.SAVE_PATH) == OK)
	manager.unlocked.erase(&"all_achievements")
	config.set_value("progression", "unlocked_achievements", manager.unlocked)
	assert(config.save(AchievementManager.SAVE_PATH) == OK)
	var reloaded := AchievementManager.new()
	root.add_child(reloaded)
	reloaded.load_progress()
	assert(reloaded.unlocked.has(&"all_achievements"))
	var reloaded_palette := ColorPaletteManager.new()
	root.add_child(reloaded_palette)
	reloaded_palette.load_progress()
	assert(reloaded_palette.selected_palette == &"solid_gold")
	print("Gold achievement tests passed.")
	quit()
